default:
  image: wangrunji0408/rcore-lab

stages:
  - build

build-ch2-job:
  stage: build
  script:
    - cd user && make all CHAPTER=2
  artifacts:
    paths:
      - user/build/bin/*.bin

build-ch3_0-job:
  stage: build
  script:
    - cd user && make all CHAPTER=3_0
  artifacts:
    paths:
      - user/build/bin/*.bin

build-ch3_1-job:
  stage: build
  script:
    - cd user && make all CHAPTER=3_1
  artifacts:
    paths:
      - user/build/bin/*.bin

build-ch3_2-job:
  stage: build
  script:
    - cd user && make all CHAPTER=3_2
  artifacts:
    paths:
      - user/build/bin/*.bin

build-ch4-job:
  stage: build
  script:
    - cd user && make all CHAPTER=4
  artifacts:
    paths:
      - user/build/elf/*.elf
