[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://gitee.com/rcore-os/riscv"]
git = "https://gitee.com/rcore-os/riscv"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"